"""Merchant catalog, inventory, policies, relationships, and RLS."""

from alembic import op

revision = "0002_merchant_commerce"
down_revision = "0001_foundation"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
    create type public.relationship_type as enum ('UPSELL','CROSS_SELL','SUBSTITUTE','BUNDLE','ACCESSORY');
    create table public.merchant_products (id uuid primary key default gen_random_uuid(), merchant_id uuid not null references public.merchants(id) on delete cascade, sku varchar(80) not null, name varchar(160) not null, brand varchar(120), category varchar(100) not null, description text, condition varchar(40) not null default 'NEW', base_price_minor bigint not null check(base_price_minor>=0), currency char(3) not null default 'INR', active boolean not null default true, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(merchant_id,sku));
    create table public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.merchant_products(id) on delete cascade, variant_key varchar(80) not null, name varchar(120) not null, attributes jsonb not null default '{}'::jsonb, price_override_minor bigint check(price_override_minor>=0), created_at timestamptz not null default now(), unique(product_id,variant_key));
    create table public.merchant_inventory (id uuid primary key default gen_random_uuid(), merchant_id uuid not null references public.merchants(id) on delete cascade, product_id uuid not null references public.merchant_products(id) on delete cascade, variant_id uuid references public.product_variants(id) on delete cascade, available_quantity integer not null default 0 check(available_quantity>=0), reserved_quantity integer not null default 0 check(reserved_quantity>=0), reorder_threshold integer, target_threshold integer, updated_at timestamptz not null default now(), unique nulls not distinct(merchant_id,product_id,variant_id));
    create table public.merchant_policies (id uuid primary key default gen_random_uuid(), merchant_id uuid not null references public.merchants(id) on delete cascade, scope varchar(12) not null check(scope in ('GLOBAL','CATEGORY','PRODUCT')), scope_reference varchar(160), base_price_minor bigint check(base_price_minor>=0), minimum_sale_price_minor bigint not null check(minimum_sale_price_minor>=0), maximum_discount_percent numeric(5,2), maximum_discount_minor bigint, negotiation_enabled boolean not null default false, max_negotiation_rounds integer not null default 0, upsell_enabled boolean not null default false, cross_sell_enabled boolean not null default false, campaign_discount_limit_percent numeric(5,2), campaign_budget_limit_minor bigint, minimum_margin_percent numeric(5,2), approval_threshold_minor bigint, valid_from timestamptz not null default now(), valid_until timestamptz, status varchar(16) not null default 'DRAFT' check(status in ('DRAFT','ACTIVE','EXPIRED','RETIRED')), version integer not null, created_at timestamptz not null default now(), unique(merchant_id,scope,scope_reference,version));
    create table public.merchant_relationships (id uuid primary key default gen_random_uuid(), merchant_id uuid not null references public.merchants(id) on delete cascade, source_product_id uuid not null references public.merchant_products(id) on delete cascade, target_product_id uuid not null references public.merchant_products(id) on delete cascade, relationship_type public.relationship_type not null, priority integer not null default 0, weight numeric(8,3) not null default 1, active boolean not null default true, created_at timestamptz not null default now(), unique(merchant_id,source_product_id,target_product_id,relationship_type));
    create index products_merchant_active_idx on public.merchant_products(merchant_id,active); create index variants_product_idx on public.product_variants(product_id); create index inventory_product_idx on public.merchant_inventory(product_id); create index policy_match_idx on public.merchant_policies(merchant_id,status,scope,valid_from); create index relationship_source_idx on public.merchant_relationships(source_product_id,active);
    create trigger products_updated before update on public.merchant_products for each row execute function public.set_updated_at(); create trigger inventory_updated before update on public.merchant_inventory for each row execute function public.set_updated_at();
    alter table public.merchant_products enable row level security; alter table public.product_variants enable row level security; alter table public.merchant_inventory enable row level security; alter table public.merchant_policies enable row level security; alter table public.merchant_relationships enable row level security;
    create policy variant_member_read on public.product_variants for select to authenticated using(exists(select 1 from public.merchant_products p join public.merchant_users mu on mu.merchant_id=p.merchant_id where p.id=product_variants.product_id and mu.user_id=auth.uid())); create policy variant_operator_write on public.product_variants for all to authenticated using(exists(select 1 from public.merchant_products p join public.merchant_users mu on mu.merchant_id=p.merchant_id where p.id=product_variants.product_id and mu.user_id=auth.uid() and mu.role in ('OWNER','ADMIN'))) with check(exists(select 1 from public.merchant_products p join public.merchant_users mu on mu.merchant_id=p.merchant_id where p.id=product_variants.product_id and mu.user_id=auth.uid() and mu.role in ('OWNER','ADMIN')));
    create policy product_member_read on public.merchant_products for select to authenticated using(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_products.merchant_id and mu.user_id=auth.uid())); create policy product_operator_write on public.merchant_products for all to authenticated using(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_products.merchant_id and mu.user_id=auth.uid() and mu.role in ('OWNER','ADMIN'))) with check(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_products.merchant_id and mu.user_id=auth.uid() and mu.role in ('OWNER','ADMIN')));
    create policy inventory_member_read on public.merchant_inventory for select to authenticated using(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_inventory.merchant_id and mu.user_id=auth.uid())); create policy inventory_operator_write on public.merchant_inventory for all to authenticated using(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_inventory.merchant_id and mu.user_id=auth.uid() and mu.role in ('OWNER','ADMIN'))) with check(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_inventory.merchant_id and mu.user_id=auth.uid() and mu.role in ('OWNER','ADMIN')));
    create policy policy_member_read on public.merchant_policies for select to authenticated using(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_policies.merchant_id and mu.user_id=auth.uid())); create policy policy_operator_write on public.merchant_policies for insert to authenticated with check(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_policies.merchant_id and mu.user_id=auth.uid() and mu.role in ('OWNER','ADMIN'))); create policy relationship_member on public.merchant_relationships for all to authenticated using(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_relationships.merchant_id and mu.user_id=auth.uid())) with check(exists(select 1 from public.merchant_users mu where mu.merchant_id=merchant_relationships.merchant_id and mu.user_id=auth.uid() and mu.role in ('OWNER','ADMIN')));
    create or replace function public.prevent_active_policy_rewrite() returns trigger language plpgsql as $$ begin if old.status='ACTIVE' then raise exception 'Active policy versions are immutable; create a new version'; end if; return new; end; $$; create trigger policy_history_immutable before update or delete on public.merchant_policies for each row execute function public.prevent_active_policy_rewrite();
    """)


def downgrade():
    op.execute(
        "drop table if exists public.merchant_relationships,public.merchant_policies,public.merchant_inventory,public.product_variants,public.merchant_products cascade; drop type if exists public.relationship_type;"
    )
